services:
  app:
    image: nlptools:01
    container_name: nlptools
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    build: 
      context: .
      network: host
      dockerfile: Dockerfile
      args:
        - DEV_nlptools=1
    ipc: host
    environment:
    #- AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
    #- AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - NVIDIA_VISIBLE_DEVICES=all
      - HOME=/app
      - DATA_DIR=/app/data
    env_file: "huggingface.env"
    ports:
      - "8888:8888"
    volumes:
      - .:/app
      - $HOME/data:/app/data